import type { Metadata } from "next";
import "./globals.css";
import Link from "next/link";
import ReduxProvider from "@/state/redux/ReduxProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
   <ReduxProvider>
    <html lang="en">
      <body>
        <div className="container">
          <nav className="navbar navbar-dark bg-dark">
            <div className="container-fluid">
              <Link className="navbar-brand" href="#">React</Link>
              <ul className="nav">
                <li className="nav-item">
                  <Link className="nav-link" href="/">Home</Link>
                </li>
                <li className="nav-item">
                  <Link className="nav-link" href="/about">About</Link>
                </li>
                <li className="nav-item">
                  <Link className="nav-link" href="/products">Products</Link>
                </li>
                <li className="nav-item">
                  <Link className="nav-link" href="/login">Login</Link>
                </li>
              </ul>
            </div>
          </nav>
          <main>
            {children}
          </main>

        </div>
      </body>
    </html>
    </ReduxProvider>
  );
}
